### ISSUE TITLE
Fuubar isn't compatible with rspec 3.0.0.rc1

### ISSUE THREAD

**Issue by ressu** [thekompanee/fuubar#66]
It looks like something changed in rspec 3.0.0 between beta2 and rc1, since Fuubar no longer works with rspec 3.0.0.rc1

```
/home/ressu/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/fuubar-2.0.0.beta2/lib/fuubar.rb:32:in `start': undefined local variable or method `configuration' for #<Fuubar:0x007f250877df60> (NameError)
    from /home/ressu/.rbenv/gems/2.1.0/gems/rspec-core-3.0.0.rc1/lib/rspec/core/reporter.rb:137:in `block in notify'
    from /home/ressu/.rbenv/gems/2.1.0/gems/rspec-core-3.0.0.rc1/lib/rspec/core/reporter.rb:136:in `each'
    from /home/ressu/.rbenv/gems/2.1.0/gems/rspec-core-3.0.0.rc1/lib/rspec/core/reporter.rb:136:in `notify'
....
```
